### ISSUE TITLE
Remove extension registry logic

### ISSUE THREAD

**Issue by jonafato** [iheartradio/Henson-Database#32]
iHeartRadio/Henson#136 added registry support in Henson's `Application` and `Extension` classes. This makes the [same logic](https://github.com/iheartradio/Henson-Database/blob/cb2b6a7fd950b689c717f5a873d3f327d0bf68ba/henson_database/__init__.py#L122-L124) in Henson-Database redundant. Once this change lands in a stable release of Henson (most likely the next release), the logic should be removed from Henson-Database.

**Comment by dirn** [comment]
This only existed inside the `migrations` branch and has been removed.
